sonar.projectKey=test-backend
sonar.projectName=Test
sonar.projectVersion=1.0
sonar.language=ts
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9500
sonar.login=sqp_7c09edc32a733078ea9df01293ab796b60429a24
